In [1]:
import pandas as pd

In [3]:
jan9_run = pd.read_csv('benchmark_runs/run_20260109_101514/run_summary.csv')

In [4]:
jan9_run

,config_file,target_id,pdb_id,doc_id,fragment_smiles,status,error_message,n_compounds_total,n_compounds_standardized,n_compounds_matched_2d,...,success_rate_rmsd,workflow_dir,best_any_n_points,best_any_pearson,best_any_spearman,best_any_r2,rmsd_n_points,rmsd_pearson,rmsd_spearman,rmsd_r2
0,generated_configs/CHEMBL1075317_6U6W_CHEMBL441...,CHEMBL1075317,6U6W,CHEMBL4414651,O=S(=O)(NC1=CC=CC=C1)C1=CC(Br)=CC=C1O,SUCCESS,NaN,71,71,61,...,68.85,CHEMBL1075317_6U6W,61.0,-0.354194,-0.349294,0.125453,61.0,-0.354194,-0.349294,0.125453
1,generated_configs/CHEMBL1075317_6U8B_CHEMBL441...,CHEMBL1075317,6U8B,CHEMBL4414651,O=S(=O)(NC1=CC=CC=C1)C1=CC(Br)=CC=C1O,SUCCESS,NaN,71,71,61,...,68.85,CHEMBL1075317_6U8B,61.0,-0.312880,-0.344930,0.097894,61.0,-0.305151,-0.339535,0.093117
2,generated_configs/CHEMBL1163125_4NUC_CHEMBL308...,CHEMBL1163125,4NUC,CHEMBL3085768,CN=NC1=CC=C(S(=O)(=O)NC2=CC=CC=N2)C=C1,SUCCESS,NaN,69,69,25,...,0.00,CHEMBL1163125_4NUC,53.0,0.184620,0.176415,0.034085,53.0,0.184620,0.176415,0.034085
3,generated_configs/CHEMBL1163125_4NUD_CHEMBL308...,CHEMBL1163125,4NUD,CHEMBL3085768,CN=NC1=CC=C(S(=O)(=O)NC2=CC=CC=N2)C=C1,SUCCESS,NaN,69,69,25,...,0.00,CHEMBL1163125_4NUD,53.0,-0.138637,-0.056579,0.019220,53.0,-0.138637,-0.056579,0.019220
4,generated_configs/CHEMBL1163125_4NUE_CHEMBL308...,CHEMBL1163125,4NUE,CHEMBL3085768,CN=NC1=CC=C(S(=O)(=O)NC2=CC=CC=N2)C=C1,SUCCESS,NaN,69,69,25,...,0.00,CHEMBL1163125_4NUE,53.0,0.046272,0.071224,0.002141,53.0,0.046272,0.071224,0.002141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,generated_configs/CHEMBL5697_6QGV_CHEMBL204083...,CHEMBL5697,6QGV,CHEMBL2040836,CCN1CCCCC1,SUCCESS,NaN,93,93,93,...,59.14,CHEMBL5697_6QGV,93.0,-0.679134,-0.684209,0.461222,93.0,-0.693025,-0.711937,0.480283
196,generated_configs/CHEMBL5747_4NR7_CHEMBL401161...,CHEMBL5747,4NR7,CHEMBL4011614,CC1=NOC(C)=C1C1=CC=C2NC=NC2=C1,FAILED_REF_MATCH,Crystal ligand (4NR7_ligand.pdb) missing fragm...,40,40,0,...,NaN,CHEMBL5747_4NR7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,generated_configs/CHEMBL5879_2CVD_CHEMBL121291...,CHEMBL5879,2CVD,CHEMBL1212916,CC1=CC=CC=C1,SUCCESS,NaN,48,48,32,...,3.12,CHEMBL5879_2CVD,48.0,-0.171065,-0.146702,0.029263,48.0,-0.171065,-0.146702,0.029263
198,generated_configs/CHEMBL6032_7XUD_CHEMBL524765...,CHEMBL6032,7XUD,CHEMBL5247652,CCNC(=O)C1=C(C)C2=C(CC(C)(C)CC2=O)N1,SUCCESS,NaN,55,55,47,...,95.74,CHEMBL6032_7XUD,49.0,-0.491381,-0.411975,0.241456,49.0,-0.501737,-0.414706,0.251740
199,generated_configs/CHEMBL6158_7MS7_CHEMBL522634...,CHEMBL6158,7MS7,CHEMBL5226343,CS(=O)(=O)N1CCCCC1,SUCCESS,NaN,50,50,39,...,0.00,CHEMBL6158_7MS7,46.0,-0.061595,-0.021713,0.003794,46.0,-0.061595,-0.021713,0.003794

In [6]:
jan9_run.sort_values(by='rmsd_pearson', ascending=True).head(10)

,config_file,target_id,pdb_id,doc_id,fragment_smiles,status,error_message,n_compounds_total,n_compounds_standardized,n_compounds_matched_2d,...,success_rate_rmsd,workflow_dir,best_any_n_points,best_any_pearson,best_any_spearman,best_any_r2,rmsd_n_points,rmsd_pearson,rmsd_spearman,rmsd_r2
20,generated_configs/CHEMBL1764940_4R4T_CHEMBL342...,CHEMBL1764940,4R4T,CHEMBL3421550,O=C(O)C1=NN(C2=CC=CC=C2)C(C2=CC=CC=C2)=C1,SUCCESS,NaN,40,40,38,...,15.79,CHEMBL1764940_4R4T,39.0,-0.822183,-0.747849,0.675985,39.0,-0.840212,-0.753012,0.705955
143,generated_configs/CHEMBL3313835_7KCF_CHEMBL483...,CHEMBL3313835,7KCF,CHEMBL4834423,O=C1C=CNC2=CC(C3=CC=CC=C3)=NN12,SUCCESS,NaN,46,46,41,...,100.00,CHEMBL3313835_7KCF,43.0,-0.812246,-0.823852,0.659744,43.0,-0.818671,-0.829971,0.670222
145,generated_configs/CHEMBL3313835_7KDB_CHEMBL483...,CHEMBL3313835,7KDB,CHEMBL4834423,O=C1C=CNC2=CC(C3=CC=CC=C3)=NN12,SUCCESS,NaN,46,46,41,...,95.12,CHEMBL3313835_7KDB,43.0,-0.795543,-0.804324,0.632888,43.0,-0.812501,-0.828785,0.660159
140,generated_configs/CHEMBL3313835_7KCC_CHEMBL483...,CHEMBL3313835,7KCC,CHEMBL4834423,O=C1C=CNC2=CC(C3=CC=CC=C3)=NN12,SUCCESS,NaN,46,46,41,...,97.56,CHEMBL3313835_7KCC,43.0,-0.803674,-0.840423,0.645891,43.0,-0.802109,-0.840423,0.643379
141,generated_configs/CHEMBL3313835_7KCC_CHEMBL551...,CHEMBL3313835,7KCC,CHEMBL5518219,C1=NNC(C2CC2)=C1,FAILED_REF_MATCH,Crystal ligand (7KCC_ligand_corrected.sdf) mis...,46,46,0,...,NaN,CHEMBL3313835_7KCC,43.0,-0.803674,-0.840423,0.645891,43.0,-0.802109,-0.840423,0.643379
18,generated_configs/CHEMBL1764940_4LUV_CHEMBL342...,CHEMBL1764940,4LUV,CHEMBL3421550,O=C(O)C1=NN(C2=CC=CC=C2)C(C2=CC=CC=C2)=C1,SUCCESS,NaN,40,40,38,...,0.00,CHEMBL1764940_4LUV,39.0,-0.754492,-0.748177,0.569258,39.0,-0.754492,-0.748177,0.569258
148,generated_configs/CHEMBL3714531_6R8R_CHEMBL433...,CHEMBL3714531,6R8R,CHEMBL4334426,CNC(=O)COC1=CC=CC=C1,SUCCESS,NaN,52,52,44,...,0.00,CHEMBL3714531_6R8R,46.0,-0.745162,-0.633201,0.555266,46.0,-0.745162,-0.633201,0.555266
157,generated_configs/CHEMBL3717_3ZCL_CHEMBL242976...,CHEMBL3717,3ZCL,CHEMBL2429765,CCC1=NN=C2C=CC=NN21,SUCCESS,NaN,60,60,26,...,96.15,CHEMBL3717_3ZCL,52.0,-0.729409,-0.593278,0.532038,52.0,-0.729409,-0.593278,0.532038
144,generated_configs/CHEMBL3313835_7KDA_CHEMBL483...,CHEMBL3313835,7KDA,CHEMBL4834423,O=C1C=CNC2=CC(C3=CC=CC=C3)=NN12,SUCCESS,NaN,46,46,41,...,97.56,CHEMBL3313835_7KDA,43.0,-0.743510,-0.760926,0.552807,43.0,-0.726630,-0.760048,0.527991
195,generated_configs/CHEMBL5697_6QGV_CHEMBL204083...,CHEMBL5697,6QGV,CHEMBL2040836,CCN1CCCCC1,SUCCESS,NaN,93,93,93,...,59.14,CHEMBL5697_6QGV,93.0,-0.679134,-0.684209,0.461222,93.0,-0.693025,-0.711937,0.480283